dist: trusty
sudo: false
language: java
jdk:
- oraclejdk8
branches:
  except:
  - /\+travis\d+$/
env:
  global:
  - MAVEN_BASE_URL=https://atomist.jfrog.io/atomist
  - secure: pWJsOGOJLPcCiKzOI3m7MfrvNdvz8DghGGj1Lkmya3LdNuRdHZLxioQPRKO891H+EAqgkSXGsYgmJ2AUqbwI+nAFI5M982OqsT/A+wDpAIMmxiSUUWZmxqxWJWxm6/BbbOGDNlyft4Dq7jEbVaEF4UXRJu/PGUq8YCECEE4r3jj+uGhjotf6txvGJFJMWLDdb1wNqUV7k2St3jWv7UmAuXe6E8LdKJgg42CQIQaOTk4csYqdzH9xsMpgKKHd6YyRJzo3th20DyDs6l0DItavj5Ek8wsnGcgoqTlcKrN14NL2hwiR0LFmDpenzJYfUqfEL+SniLuw5HQRg6DE9YCNQ2Z+2eHVdNOqdyBGndZBmowoCCooJ4JRVeiyZWhpRgfuM95mG+IHr+CNIU+540G0pzOaDs3YO2yboL/Z5VcJBABZEYpyfZ2bjZpDhyxMB0s7Ejh1THF2ENFP1lRFeHa5otXREkBWbdSAOMMBiMjkyhvDFvt48wdsjbjflD01uEnephnsgn90JNvwaqtqKl2pCUOtWfrdAa9ViCjA/ciBhd8MbOO5VPDAkNRRw5JX5dbjsgf/kdr2tJShOPvhoTq6ehF8RKpPPx9NoPCNVxbTDCkmvtumiD3QcjkREuo8pcGyOmZvqgGm9qnolOPB+/ADuPyjyfbSxu4JHY3pTrrknos=
  - secure: EwSeGP/mRsZBQWEDUEtU2uHJob6caIP+2M9y449hgWukRwl2SxdOb+FfjeURgHwGszvIkt8fdZIL0vSpeRFgUdMb5T5eV4qpAmpRsEV8p7cfB1CYrunGYPki3Z12DQg/YwnzbYXq4NQsYGoxmQFotxoZjpqsfyayOjARJMmHq0X/S+UeC0JlDUGAvJNHDXgOxfc+ALUwCIgK+0J/oSuJSjI1gF5vcX/pjycp++o3hOnkOmrv0SqnRW6YZjt/GSXm8Nc2M4YXnRL/vH1lpkjWPP9EGmxZ/Wbr3DkuvKGUz6E4FnEG80RP6CNPqJKTkQGkX+/KqCgqzDo3jIHzU1Rr+wV8qeSBhN9Wg23IVYololyMr3dgmZmtP+85ZXkvogy97qN3SURWsctlUYg8ypKUPwtf1ekBqPFJuyU0ND1Cd9dXI4iKAAVjOSWwN53y4zikrRoIx5NbvUCPIY/SRH3AWkgAYqCmeDDzLZnT5y/tSrvS/0Nv27ve8Xdx6h5qsunmTIUkZAyzgIt1PELwf5ffZnpu/234Wx/BE4Sc56H2Tkfg3Cq8ia3Xo60UwX1IbUoqOvT2NyqJ3aPIxomOaBB3ASNT0FliLH3kPhlfRv/tP2fAuiOXtStmBXvBWReqDJq1I5z9ztAyu6PptMi4TiWeYCK6dudwdH8+WK4+zuwaHSY=
  - secure: WWXXwjZSQKnsWHByECa/g3t6dvoF7tLchiSYaYS04lHCirX6YQQtzbPJue2Qh2Ov1xAUHTjcqTq0WJTlvQDKSoEa4fJo/55nlmYyNDd2imZfef8ria0Vrm59IXxQmFqA6SAQF/rFiEDoJlHm9s30CA2JfKK8bVZ4GvbIP8lUwfv/46DwErKphAHgAfiKyzJKHqWbKorRWCNTAnfsy/SDRUUfOyme7WE5XZ+opClb/zbI/bpWwOuHTIobnQYVH0Jno5pVJowUQsyWVVJHp2H8D2gSD9m5eMfE1kcl8piIUmdDgkuqegBUP/WrZ+iGgvIXEFWNvQu6dxWO92TXiizCKAR2VGdGyRF0FQY3uuiP0OrLo72Y/eTP+Hf8CXOWfznY2WD7yd/kN4u2W3+HYOAjehe6dIL7X9n/f2GiUa5rN77jjXbewEbFtg6mPFdbcdtpeaa+Za9zz+PvKXec44+tVF1p7kS/wuhh9o949koA+Q8tTm2nxXHH0ztBspxmZd+pfaKpnD6Ve0MhfnAM0VDxvxFoTiNqxhm+lwhz95uZjnSMUtuOIs7IgSRz7/xYicbs1tlnF9ogEoVp/I2rR3XlJVdT6ayjZT3pmAPOfjaLDvGf+gu1lBbwb8kpRTdI77VrTCCzm4PGdkxztU6C/hoLPZIlEYMHLXpRaj40VBl/vNc=
install:
- nvm install 6.9.2
script: bash .atomist/build/travis-build.bash
notifications:
  email: false
  webhooks:
    urls:
    - https://webhook.atomist.com/travis
    on_success: always
    on_failure: always
    on_start: always
cache:
  directories:
  - $HOME/.atomist
