Feature: Tests from AddDockerMavenPlugin.rt
  This file was autogenerated.
  It aims to avoid collisions, not remove redundancy.
  You can probably consolidate a lot of the elements.




  Scenario: AddDockerMavenPlugin is added to your project by AddAddDockerMavenPlugin
    Given the pom root
    When AddDockerMavenPlugin is executed
    Then the pom file contains the property
    Then the pom file contains docker-maven-plugin
