Feature: Tests from AddJenkinsfile.rt
  This file was autogenerated.
  It aims to avoid collisions, not remove redundancy.
  You can probably consolidate a lot of the elements.




  Scenario: Jenkinsfile is added to your project by AddJenkinsfile
    Given the archive root
    When AddJenkinsfile provides all the parameters
    Then the Jenkinsfile exists
    Then the Jenkinsfile contains the jenkins agent
    Then the Jenkinsfile contains the channel
    Then the Jenkinsfile contains the teamdomain
    Then the Jenkinsfile contains the slack api token
    Then the Jenkinsfile contains the jdk name
    Then the Jenkinsfile contains the main branch
    Then the Jenkinsfile contains the build command
    Then the Jenkinsfile contains the artifacts location
    Then the Jenkinsfile contains the test command
    Then the Jenkinsfile contains the sonarqube command
